---
title: "Homework 4 Business Analytics"
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
  word_document: default
---

**1.**

```{r}
tahoe<-read.csv("tahoe_healthcare_data.csv")
```

a)  

```{r}
library(tree)
tree.tahoe<-tree(readmit30 ~ . , data = tahoe, split = "deviance",minsize=4,mindev=1e-3)
plot(tree.tahoe)
text(tree.tahoe,pretty=0)
tree.tahoe
```

b)  

```{r}
cv.tree.tahoe<-cv.tree(tree.tahoe, FUN = prune.tree, K=7)
plot(cv.tree.tahoe)
```

According to the above results, the optimal size is 4.

```{r}
prune.cv.tree.tahoe = prune.tree(tree.tahoe, best=4)
plot(prune.cv.tree.tahoe)
text(prune.cv.tree.tahoe,pretty=0)
prune.cv.tree.tahoe
```

c)  

According to the tree above, we would assign CareTacker to patients with comobidity score \> 121.5 or severity.score \> 31.5 .

```{r}
percentage.withCareTacker = sum(tahoe$comorbidity.score > 121.5 | tahoe$severity.score > 31.5, na.rm=TRUE)/nrow(tahoe)
percentage.withCareTacker
```

If we assign CareTacker to patients with at a probability of at least 15% of bein readmitted, about 44.7% of patients would receive CareTacker.

d) e) ?? not sure
```{r}

# demographic parity - P(C(X,A) = 1 |A = 1) = P(C(X,A) = 1 |A = 0)
number.females = sum(tahoe$female==1)
number.non_females = sum(tahoe$female==0)

number.females.withCareTacker = sum(predict(prune.cv.tree.tahoe,newdata =tahoe[tahoe$female==1,])>0.15)
number.non_females.withCareTacker = sum(predict(prune.cv.tree.tahoe,newdata =tahoe[tahoe$female==0,])>0.15)

p1 = number.females.withCareTacker / number.females
p0 = number.non_females.withCareTacker / number.non_females

# unawareness - P(C(X, A) = 1) = P(C(X) = 1)

tahoe2 <- tahoe
tahoe2$female <- c(rep(0, nrow(tahoe)))

number.withCareTacker.X_A = sum(predict(prune.cv.tree.tahoe,newdata =tahoe)>0.15)
number.withCareTacker.X = sum(predict(prune.cv.tree.tahoe,newdata = tahoe2)>0.15)


p.XA = number.withCareTacker.X_A / nrow(tahoe)
p.X = number.withCareTacker.X / nrow(tahoe)

```

**2.**

```{r}
college<-read.csv("CollegeData-2.csv")
college<-na.omit(college)
```

a)  

```{r}
library(factoextra)
college.num<-college[,-1]
college.scaled<-scale(college.num)
fviz_nbclust(college.scaled,kmeans,method="wss",k.max=50)
```

According to the graph above, I would choose K = 6.

b)  

```{r}
college.sorted <- college[order(college$INSTNM), ][1:100,]
college.sorted<-data.frame(scale(college.sorted[,-1]))
set.seed(2)
hc.average=hclust(dist(college.sorted),method="average")
plot(college.sorted,col=cutree(hc.average,4))
```

```{r}
fviz_nbclust(college.sorted,kmeans,method="wss",k.max=50)
```
